export const ACT_ADD_TO_CART = "ADD_TO_CART";
export const ACT_REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ACT_UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const ACT_PURCHASE = "PURCHASE";
export const CHANGE_MESS = "CHANGE_MESS";
export const UPDATE_STOCK = "UPDATE_STOCK"